pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    rimraf dist/*
    npm run clean && npm run build:browser && npm run build:node
  displayName: 'build and test'
