pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    rimraf dist/*
    cross-env RUNTIME_ENV=browser webpack --progress --colors --display-chunks --config ./build/webpack.browser.js
    cross-env RUNTIME_ENV=node webpack --progress --colors --display-chunks --config ./build/webpack.node.js
    npm run clean && cross-env RUNTIME_ENV=node webpack --config ./build/webpack.analyze.js
    npm run clean && cross-env RUNTIME_ENV=browser webpack --config ./build/webpack.analyze.js
    npm run clean && cross-env RUNTIME_ENV=browser webpack --config ./build/webpack.analyze.js  
    npm run clean && npm run build:browser && npm run build:node
  displayName: 'build and test'
