pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    rimraf dist/*
    npm run clean && npm run build:browser && npm run build:node
    npm run clean && cross-env RUNTIME_ENV=node webpack --config ./build/webpack.analyze.js
    npm run clean && cross-env RUNTIME_ENV=browser webpack --config ./build/webpack.analyze.js
    npm run test:browser && npm run test:node
  displayName: 'build and test'
